blank_issues_enabled: false
contact_links:
  - name: 💬 Discussões
    url: https://github.com/danzokka/CMS-Portfolio/discussions
    about: Para perguntas gerais e discussões sobre o projeto
  - name: 📚 Documentação
    url: https://github.com/danzokka/CMS-Portfolio/wiki
    about: Consulte a documentação do projeto
