"use server"

import { Skill } from "../types/skills";

export async function getSkills() {
  try {
    // Simulate fetching skills from an API or database
    const skills: Skill[] = [
      {
        id: '1',
        name: "JavaScript",
        description: "Dynamic programming language for web development",
        icon: "https://go-skill-icons.vercel.app/api/icons?i=js",
        category: "Programming Language",
        level: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '2',
        name: "React",
        description: "JavaScript library for building user interfaces",
        icon: "https://go-skill-icons.vercel.app/api/icons?i=react",
        category: "Frontend Framework",
        level: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '3',
        name: "Ubuntu",
        description: "Ubuntu server and desktop for enterprise and personal use",
        icon: "https://go-skill-icons.vercel.app/api/icons?i=ubuntu",
        category: "Operating System",
        level: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '4',
        name: "JWT",
        description: "Compact, URL-safe means of representing claims to be transferred between two parties",
        icon: "https://go-skill-icons.vercel.app/api/icons?i=jwt",
        category: "Authentication",
        level: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '5',
        name: "Drizzle ORM",
        description: "Type-safe database ORM for TypeScript",
        icon: "https://go-skill-icons.vercel.app/api/icons?i=drizzle",
        category: "ORM",
        level: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '6',
        name: "TypeScript",
        description: "Superset of JavaScript with static typing",
        icon: "https://go-skill-icons.vercel.app/api/icons?i=typescript",
        category: "Programming Language",
        level: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '7',
        name: "Next.js",
        description: "React framework for production",
        icon: "https://go-skill-icons.vercel.app/api/icons?i=nextjs",
        category: "Framework",
        level: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '8',
        name: "Tailwind CSS",
        description: "Utility-first CSS framework",
        icon: "https://go-skill-icons.vercel.app/api/icons?i=tailwindcss",
        category: "CSS Framework",
        level: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '9',
        name: "Docker",
        description: "Containerization platform",
        icon: "https://go-skill-icons.vercel.app/api/icons?i=docker",
        category: "DevOps",
        level: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '10',
        name: "Git",
        description: "Version control system",
        icon: "https://go-skill-icons.vercel.app/api/icons?i=git",
        category: "Version Control",
        level: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '11',
        name: "NestJS",
        description: "Framework for building efficient, scalable Node.js server-side applications",
        icon: "https://go-skill-icons.vercel.app/api/icons?i=nestjs",
        category: "Framework",
        level: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '12',
        name: "PostgreSQL",
        description: "Powerful, open source object-relational database system",
        icon: "https://go-skill-icons.vercel.app/api/icons?i=postgresql",
        category: "Database",
        level: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '13',
        name: "MongoDB",
        description: "NoSQL database for modern applications",
        icon: "https://go-skill-icons.vercel.app/api/icons?i=mongodb",
        category: "Database",
        level: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '14',
        name: "AWS",
        description: "Cloud computing platform",
        icon: "https://go-skill-icons.vercel.app/api/icons?i=aws",
        category: "Cloud Technology",
        level: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '15',
        name: 'Prisma',
        description: 'Next-generation ORM for Node.js and TypeScript',
        icon: 'https://go-skill-icons.vercel.app/api/icons?i=prisma',
        category: 'ORM',
        level: 7,
        createdAt: new Date(),
        updatedAt: new Date(), 
      }
    ];
    return skills;
  } catch (error) {
    console.error("[Get Skills] Failed to fetch skills:", error);
    return [];
  }
}